### ISSUE TITLE
Deploy to NPM

### ISSUE THREAD

**Issue by eordano** [Dig-Doug/rules_typescript_proto#7]
Hey @Dig-Doug please contact me so we can have this deployed on NPM!

**Comment by Dig-Doug** [comment]
Hey @eordano, can you explain a bit more about your use case and why you need this project deployed to NPM?

I recommend referencing this project using the standard [bazel external dependency features](https://docs.bazel.build/versions/master/external.html) in your `WORKSPACE` as described in the `README`.

I'm hesitant to start publishing versions on NPM because it will increase the amount of maintenance required for the library.

**Comment by eordano** [comment]
Hmm, I also prefer the external dependencies, yet I thought that this might have been something desirable.
